Repository AndcultureCode/AndcultureCode.JavaScript.Testing, pull requests merged in 2020-10, with the labels that each got.

#13 Feature/add test utility for generating filename
  .vscode/settings.json
  src/utilities/test-utils.test.ts
  src/utilities/test-utils.ts
Labels: enhancement

#11 Update exports from index.ts to include TestUtils
  src/index.ts
Labels: bug

#14 Add randomObject util
  src/utilities/test-utils.test.ts
  src/utilities/test-utils.ts
Labels: hacktoberfest-approved

#16 Random case util
  src/utilities/test-utils.test.ts
  src/utilities/test-utils.ts
Labels: hacktoberfest-approved
